#############################################################################
# Makefile for building: GigaPi
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sat Mar 23 22:56:09 2013
# Project:  GigaPi.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile GigaPi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../wiringPi/wiringPi -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -L/home/pi/GigaPi/../wiringPi/wiringPi/ -lwiringPi -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		settings.cpp \
		adjustments.cpp \
		progress.cpp \
		numberedit.cpp \
		editbox.cpp moc_mainwindow.cpp \
		moc_settings.cpp \
		moc_adjustments.cpp \
		moc_progress.cpp \
		moc_numberedit.cpp \
		moc_editbox.cpp
OBJECTS       = main.o \
		mainwindow.o \
		settings.o \
		adjustments.o \
		progress.o \
		numberedit.o \
		editbox.o \
		moc_mainwindow.o \
		moc_settings.o \
		moc_adjustments.o \
		moc_progress.o \
		moc_numberedit.o \
		moc_editbox.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GigaPi.pro
QMAKE_TARGET  = GigaPi
DESTDIR       = 
TARGET        = GigaPi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_settings.h ui_mainwindow.h ui_adjustments.h ui_progress.h ui_numberedit.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GigaPi.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile GigaPi.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile GigaPi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GigaPi1.0.0 || $(MKDIR) .tmp/GigaPi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GigaPi1.0.0/ && $(COPY_FILE) --parents mainwindow.h settings.h adjustments.h progress.h numberedit.h editbox.h .tmp/GigaPi1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp settings.cpp adjustments.cpp progress.cpp numberedit.cpp editbox.cpp .tmp/GigaPi1.0.0/ && $(COPY_FILE) --parents settings.ui mainwindow.ui adjustments.ui progress.ui numberedit.ui .tmp/GigaPi1.0.0/ && (cd `dirname .tmp/GigaPi1.0.0` && $(TAR) GigaPi1.0.0.tar GigaPi1.0.0 && $(COMPRESS) GigaPi1.0.0.tar) && $(MOVE) `dirname .tmp/GigaPi1.0.0`/GigaPi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GigaPi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_settings.cpp moc_adjustments.cpp moc_progress.cpp moc_numberedit.cpp moc_editbox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_settings.cpp moc_adjustments.cpp moc_progress.cpp moc_numberedit.cpp moc_editbox.cpp
moc_mainwindow.cpp: settings.h \
		editbox.h \
		numberedit.h \
		adjustments.h \
		progress.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_settings.cpp: editbox.h \
		numberedit.h \
		settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

moc_adjustments.cpp: adjustments.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) adjustments.h -o moc_adjustments.cpp

moc_progress.cpp: progress.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) progress.h -o moc_progress.cpp

moc_numberedit.cpp: numberedit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) numberedit.h -o moc_numberedit.cpp

moc_editbox.cpp: numberedit.h \
		editbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editbox.h -o moc_editbox.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_settings.h ui_mainwindow.h ui_adjustments.h ui_progress.h ui_numberedit.h
compiler_uic_clean:
	-$(DEL_FILE) ui_settings.h ui_mainwindow.h ui_adjustments.h ui_progress.h ui_numberedit.h
ui_settings.h: settings.ui
	/usr/bin/uic-qt4 settings.ui -o ui_settings.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_adjustments.h: adjustments.ui
	/usr/bin/uic-qt4 adjustments.ui -o ui_adjustments.h

ui_progress.h: progress.ui
	/usr/bin/uic-qt4 progress.ui -o ui_progress.h

ui_numberedit.h: numberedit.ui
	/usr/bin/uic-qt4 numberedit.ui -o ui_numberedit.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		settings.h \
		editbox.h \
		numberedit.h \
		adjustments.h \
		progress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		settings.h \
		editbox.h \
		numberedit.h \
		adjustments.h \
		progress.h \
		ui_mainwindow.h \
		../wiringPi/wiringPi/wiringPi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

settings.o: settings.cpp settings.h \
		editbox.h \
		numberedit.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

adjustments.o: adjustments.cpp adjustments.h \
		ui_adjustments.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adjustments.o adjustments.cpp

progress.o: progress.cpp progress.h \
		ui_progress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progress.o progress.cpp

numberedit.o: numberedit.cpp numberedit.h \
		ui_numberedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numberedit.o numberedit.cpp

editbox.o: editbox.cpp editbox.h \
		numberedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editbox.o editbox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_adjustments.o: moc_adjustments.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adjustments.o moc_adjustments.cpp

moc_progress.o: moc_progress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_progress.o moc_progress.cpp

moc_numberedit.o: moc_numberedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numberedit.o moc_numberedit.cpp

moc_editbox.o: moc_editbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editbox.o moc_editbox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

